### ISSUE TITLE
Problema con Plugin Promote MDN

### ISSUE THREAD

**Issue by Sessy91** [MozillaItalia/PassoPasso#16]
Link: [http://passopasso.mte90.net/attivita/installa-promote-mdn-sul-blog/]

Sono andato nella pagina wordopress.com e andando nelle opzioni di plugin non ho trovato modo in cercare o installare MDN..

Suggerisco che venga modificato il task con l'aggiunta di una descrizione sul non funzionamento di esso in wordpress.com o almeno che venga fixato tutto!

**Comment by Mte90** [comment]
Non può essere fixato in questo il .com non permette i plugin quindi l'unica é aggiornare il task
