### ISSUE TITLE
Problema sul Task "Segnala siti italiani malfunzionanti"

### ISSUE THREAD

**Issue by Sessy91** [MozillaItalia/PassoPasso#17]
Link: http://www.arewecompatibleyet.com/#list:it50
# Problema

Andando sul link per ottenere la visualizzazione dei siti da monitorare, mi sono imbattuto in una schermata senza possibilità di scelta dei siti. Ho provato più volte anche riavviando tutto ad entrare nella pagina, ma mi si presenta la stessa medesima situazione. Lascio l'allegato della pagina che ho dinanzi.
# Come risolvere

Suggerisco di verificare che sia funzionante il link o che venga controllata la pagina in questione.
![ddd](https://cloud.githubusercontent.com/assets/17323500/16598434/494b7860-42fe-11e6-8a16-9b3a40a36d1f.png)

**Comment by Mte90** [comment]
Il sito non sembra funzionare, adesso apro un ticket, https://github.com/hallvors/mobilewebcompat/issues/16

**Comment by Sessy91** [comment]
Grazie Daniele =) !!

**Comment by Mte90** [comment]
Non si hanno notizie forse é il caso di togliere quel link nel frattempo

**Comment by Mte90** [comment]
Il sito è stato fixato con una mia pr.
