### ISSUE TITLE
[Sito] Riunione

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/PassoPasso#18]
- [x] Programma riunione
- [x] Scegliere data - http://doodle.com/poll/mptz2ziaitp8mvq5#table
- [x] Partecipanti
# Programma
- Che cosa non funziona?
  - Che cosa si può semplificare?
  - Che cosa manca come funzionalità?
  - Nuovo tema https://github.com/MozillaItalia/PassoPasso/issues/14
- Che argomenti vorresti trovare?
- Che attività sono fatte male?
- Migliorare il testo di esempio dei ticket #5
- Testo di esempio #19
- Come fare per i badge?
  - 1 - Un badge con un numero per indicare il livello
  - 2 - Grafica diversa per ogni task anche se della stessa serie

Partecipanti:
@mte90, @giovannilamotta, @edovio

**Comment by Giovannilamotta** [comment]
Eccolo

**Comment by edovio** [comment]
Eccomi!!! Appena termino il Vadevecum ci sono!!! XD

**Comment by Mte90** [comment]
Doodle per scegliere la data della riunione http://doodle.com/poll/mptz2ziaitp8mvq5#table

**Comment by Mte90** [comment]
Etherpad riunione: https://public.etherpad-mozilla.org/p/mozita-passopasso-2016

Riassunto:
- Ricevuti ottimi feedback e nuove idee da implementare, ticket asap
- Giovanni e Matteo sono stati promossi come editor e hanno il vouch su mozillians
